# Generated by Django 3.1.7 on 2021-05-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singerpost',
            old_name='title',
            new_name='sing_name',
        ),
        migrations.AddField(
            model_name='singerpost',
            name='sing_Born',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='singerpost',
            name='sing_Genres',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='singerpost',
            name='sing_career',
            field=models.TextField(default=''),
        ),
    ]
