# Generated by Django 3.1.7 on 2021-05-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210504_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingerPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=200, null=True)),
                ('content', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='singer_img')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
